//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module;Device;Code;Description
        ///MASTER;M4500;E00;Przerwany obwód bezpieczeństwa stopów awaryjnych
        ///MASTER;M4501;E01;Przerwany obwód bezpieczeństwa bramek zespołu gilotyny
        ///MASTER;M4502;E02;Przerwany obwód bezpieczeństwa bramek zespołu rozcinania
        ///MASTER;M4503;E03;
        ///MASTER;M4504;E04;Przerwany obwód bezpieczeństwa bramek zespołu Z
        ///MASTER;M4505;E05;
        ///MASTER;M4506;E06;
        ///MASTER;M4507;E07;
        ///MASTER;M4508;E08;
        ///MASTER;M4509;E09;
        ///MASTER;M4510;E10;
        ///MASTER;M4511;E11;
        ///MASTER;M4512;E12;
        ///MASTER;M4513;E13;
        ///MASTER;M4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Evromat2022_MA595_Awarie {
            get {
                return ResourceManager.GetString("Evromat2022_MA595_Awarie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number;Opis
        ///1;Lokalizacja 1
        ///2;Lokalizacja 2
        ///3;Lokalizacja 3
        ///4;Lokalizacja 4
        ///5;Lokalizacja 5
        ///6;Lokalizacja 6
        ///7;Lokalizacja 7
        ///8;Lokalizacja 8
        ///9;Lokalizacja 9
        ///10;Lokalizacja 10
        ///11;Lokalizacja 11
        ///12;Lokalizacja 12
        ///13;Lokalizacja 13
        ///14;Lokalizacja 14
        ///15;Lokalizacja 15
        ///16;Lokalizacja 16
        ///17;Lokalizacja 17
        ///18;Lokalizacja 18
        ///.
        /// </summary>
        internal static string Lista_Bramek {
            get {
                return ResourceManager.GetString("Lista_Bramek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
